- name: Create user in managed 1
  hosts: pod-marlin-managed1
  become: yes
  tasks:
    - name: create user ops
      user:
        name: "{{ item }}"
        password: "{{ pass | password_hash ('sha512') }}"
        state: present
      loop: "{{ list_user_ops_managed1 }}"
    - name: create user dev
      user:
        name: "{{ item }}"
        password: "{{ pass | password_hash ('sha512') }}"
        state: present
      loop: "{{ list_user_dev_managed1 }}"
      
- name: Create user in managed 2
  hosts: pod-marlin-managed2
  become: yes
  tasks:
    - name: create user ops
      user:
        name: "{{ item }}"
        password: "{{ pass | password_hash ('sha512') }}"
        state: present
      loop: "{{ list_user_ops_managed2 }}"
    - name: create user dev
      user:
        name: "{{ item }}"
        password: "{{ pass | password_hash ('sha512') }}"
        state: present
      loop: "{{ list_user_dev_managed2 }}"
