---
- name: create user using vars fron encrypt file
  hosts: pod
  become: true
  vars_files:
    - quiz-Secret.yml

  tasks:
    - name: create user
      user:
        name: "{{ username }}"
        password: "{{ passwd | password_hash('sha512') }}"
